name: adguardhome

services:
  adguardhome:
    container_name: adguardhome
    restart: on-failure:5
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 53:53
      - 100:100/tcp
      - 3000:3000/tcp
    volumes:
      - adguardhome-data:/opt/adguardhome/conf
      - adguardhome-data:/opt/adguardhome/work
volumes:
  adguardhome-data:
    driver: local
